module.exports = {
    "name": 'col',
    "props": [{
        "name": "span",
        "label": "列数",
        "value": "number",
        default: 24
    }, {
        "name": "offset",
        "label": "左侧的间隔格数",
        "value": "number",
    }, {
        "name": "push",
        "label": "向右移动格数",
        "value": "number",
    }, {
        "name": "pull",
        "label": "向左移动格数",
        "value": "number",
    }, {
        "name": "xs",
        "label": "xs",
        "value": "string",
    }, {
        "name": "sm",
        "label": "sm",
        "value": "string",
    }, {
        "name": "md",
        "label": "md",
        "value": "string",
    }, {
        "name": "lg",
        "label": "lg",
        "value": "string",
    }, {
        "name": "xl",
        "label": "xl",
        "value": "string",
    }, {
        "name": "tag",
        "label": "tag",
        "value": "string",
        default: 'div'
    }]
}