module.exports = {
    "name": 'table',
    "exposeProperty": ["load", "clear"],
    "props": [{
        "name": "cols",
        "label": "设置列",
        "value": ["object"],
        "format": [{
            "name": "fixed",
            "label": "fixed",
            "value": "select",
            "options": ["left", "right"]
        }, {
            "name": "label",
            "label": "label",
            "value": "string"
        }, {
            "name": "prop",
            "label": "prop",
            "value": "string"
        }, {
            "name": "minWidth",
            "label": "min-width",
            "value": "string"
        }, {
            "name": "scope",
            "label": "scope",
            "value": "slot",
            scope: 'scope'
        }, {
            "name": "align",
            "label": "align",
            "value": "select",
            "options": ['left', 'center', 'right']
        }, {
            "name": "type",
            "label": "type",
            "value": "select",
            "options": ['selection', 'index', 'expand']
        }]
    }, {
        "name": "isLoad",
        "label": "是否立即加载",
        "value": "boolean"
    }, {
        "name": "pagination",
        "label": "分页器",
        "value": "boolean"
    }, {
        "name": "height",
        "label": "height",
        "value": "string"
    }, {
        "name": "maxHeight",
        "label": "maxHeight",
        "value": "string"
    }, {
        "name": "size",
        "label": "size",
        "value": "select",
        "options": ['medium', 'small', 'mini']
    }, {
        "name": "fit",
        "label": "宽度是否自撑开",
        "value": "boolean",
        "default": true
    }, {
        "name": "method",
        "label": "请求method",
        "value": "string",
        "default": "get"
    }, {
        "name": "url",
        "label": "请求url",
        "value": "string"
    }, {
        "name": "pageName",
        "default": "page",
        "label": "请求page字段",
        "value": "string"
    }, {
        "name": "pageSizeName",
        "default": "pageSize",
        "label": "请求pageSize字段",
        "value": "string"
    }, {
        "name": "totalName",
        "label": "响应total字段",
        "default": "total",
        "value": "string"
    }, {
        "name": "itemsName",
        "label": "响应items字段",
        "default": "items",
        "value": "string"
    }, {
        "name": "marginTop",
        "label": "margin-top(px)",
        "value": "number"
    }, {
        "name": "marginBottom",
        "label": "margin-bottom(px)",
        "value": "number"
    }]
}